from tkinter import *
root=Tk()#screen
from tkinter import messagebox
root.geometry("500x500")
root.title("address book")
root.config(background="maroon")
myAddressBook={}
def clear_all():
    yr1.delete(0,END)
    yr2.delete(0,END)
    yr3.delete(0,END)
    yr4.delete(0,END)
    yr5.delete(0,END)
def add_items():
    Key=yr1.get()
    if Key=="":
        messagebox.showinfo("Error","Name cannot be empty")
    else :
        if Key not in myAddressBook.keys():
            listbox.insert(END,Key)
        myAddressBook[Key]=( yr1.get(),yr2.get(),yr3.get(),yr4.get(),yr5.get())
        clear_all()
Cal=Label(root,text="Addressbook ",fg="royal blue",bg="maroon",font=("times",15,"bold"))
Cal.grid(row=1,column=1,pady=25)
yr1=Entry(root,width=25)
yr1.place(x=700,y=150)
yr2=Entry(root,width=25)
yr2.place(x=700,y=200)
yr3=Entry(root,width=25)
yr3.place(x=700,y=250)
yr4=Entry(root,width=25)
yr4.place(x=700,y=300)
yr5=Entry(root,width=25)
yr5.place(x=700,y=350)
submit=Button(root,text="open",fg="RoyalBlue1",bg="maroon")
submit.grid(row=1,column=2,padx=50)
submit1=Button(root,text="add",fg="RoyalBlue1",bg="maroon")
submit1.place(x=500,y=300)
submit2=Button(root,text="save",fg="RoyalBlue1",bg="maroon")
submit2.place(x=400,y=450)
submit3=Button(root,text="delete",fg="RoyalBlue1",bg="maroon")
submit3.place(x=400,y=350)
submit3=Button(root,text="Edit",fg="RoyalBlue1",bg="maroon")
submit3.place(x=350,y=350)
yr1=Entry(root,width=25)
yr1.place(x=700,y=150)
yr2=Entry(root,width=25)
yr2.place(x=700,y=200)
yr3=Entry(root,width=25)
yr3.place(x=700,y=250)
yr4=Entry(root,width=25)
yr4.place(x=700,y=300)
yr5=Entry(root,width=25)
yr5.place(x=700,y=350)
Cal5=Label(root,text="email:",fg="royal blue",bg="maroon",font=("times",15,"bold"))
Cal5.place(x=650,y=250)
Cal6=Label(root,text="adress:",fg="royal blue",bg="maroon",font=("times",15,"bold"))
Cal6.place(x=650,y=200)
Cal7=Label(root,text="name: ",fg="royal blue",bg="maroon",font=("times",15,"bold"))
Cal7.place(x=650,y=150)
Cal8=Label(root,text="mobile: ",fg="royal blue",bg="maroon",font=("times",15,"bold"))
Cal8.place(x=650,y=300)
Cal9=Label(root,text="birthday: ",fg="royal blue",bg="maroon",font=("times",15,"bold"))
Cal9.place(x=650,y=350)

frame=Frame(root)
scrollbar=Scrollbar(frame,orient="vertical")
scrollbar.pack(side=RIGHT,fill=Y)
listbox=Listbox(frame,width=70,yscrollcommand=scrollbar.set,bg="red")
listbox.pack(side=LEFT,padx=5)
scrollbar.config(command=listbox.yview)
frame.grid(row=2,column=1,padx=50,pady=50)
root.mainloop()